// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was automatically generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "basePath": "/api",
    "definitions": {
        "model.CreateAlumniRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string"},
                "nim": {"type": "string"},
                "email": {"type": "string"},
                "no_hp": {"type": "string"},
                "angkatan": {"type": "integer"},
                "ipk": {"type": "number"}
            }
        },
        "model.UpdateAlumniRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string"},
                "email": {"type": "string"},
                "no_hp": {"type": "string"},
                "ipk": {"type": "number"}
            }
        },
        "model.CreatePekerjaanRequest": {
            "type": "object",
            "properties": {
                "alumni_id": {"type": "string"},
                "nama_perusahaan": {"type": "string"},
                "posisi_jabatan": {"type": "string"},
                "bidang_industri": {"type": "string"},
                "lokasi_kerja": {"type": "string"},
                "tanggal_mulai_kerja": {"type": "string"},
                "status_pekerjaan": {"type": "string"}
            }
        },
        "model.UpdatePekerjaanRequest": {
            "type": "object",
            "properties": {
                "nama_perusahaan": {"type": "string"},
                "posisi_jabatan": {"type": "string"},
                "bidang_industri": {"type": "string"},
                "lokasi_kerja": {"type": "string"},
                "tanggal_mulai_kerja": {"type": "string"},
                "status_pekerjaan": {"type": "string"}
            }
        }
    },
    "host": "localhost:3000",
    "info": {
        "contact": {},
        "description": "API untuk mengelola data alumni dengan MongoDB menggunakan Clean Architecture",
        "title": "Alumni Management API",
        "version": "1.0"
    },
    "paths": {
        "/alumni": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Get all alumni",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "limit", "in": "query", "type": "integer", "default": 10},
                    {"name": "sortBy", "in": "query", "type": "string", "default": "created_at"},
                    {"name": "order", "in": "query", "type": "string", "default": "desc"},
                    {"name": "search", "in": "query", "type": "string"}
                ],
                "responses": {
                    "200": {"description": "alumni list with metadata"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Create new alumni",
                "parameters": [
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/model.CreateAlumniRequest"}}
                ],
                "responses": {
                    "201": {"description": "created alumni"},
                    "400": {"description": "Request tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/alumni/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Get alumni by ID",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "alumni data"},
                    "400": {"description": "ID tidak valid"},
                    "404": {"description": "Alumni tidak ditemukan"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Update alumni",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/model.UpdateAlumniRequest"}}
                ],
                "responses": {
                    "200": {"description": "updated alumni"},
                    "400": {"description": "ID tidak valid"},
                    "500": {"description": "error"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Soft delete alumni",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "400": {"description": "ID tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/alumni/tanpa-pekerjaan": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Alumni"],
                "summary": "Get alumni without pekerjaan",
                "responses": {
                    "200": {"description": "alumni list"},
                    "500": {"description": "error"}
                }
            }
        },
        "/pekerjaan": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Get all pekerjaan",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "limit", "in": "query", "type": "integer", "default": 10},
                    {"name": "sortBy", "in": "query", "type": "string", "default": "created_at"},
                    {"name": "order", "in": "query", "type": "string", "default": "desc"},
                    {"name": "search", "in": "query", "type": "string"}
                ],
                "responses": {
                    "200": {"description": "pekerjaan list with metadata"},
                    "500": {"description": "error"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Create new pekerjaan",
                "parameters": [
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/model.CreatePekerjaanRequest"}}
                ],
                "responses": {
                    "201": {"description": "created pekerjaan"},
                    "400": {"description": "Request tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/pekerjaan/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Get pekerjaan by ID",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "pekerjaan data"},
                    "400": {"description": "ID tidak valid"},
                    "404": {"description": "Pekerjaan tidak ditemukan"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Update pekerjaan",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/model.UpdatePekerjaanRequest"}}
                ],
                "responses": {
                    "200": {"description": "updated pekerjaan"},
                    "400": {"description": "ID tidak valid"},
                    "500": {"description": "error"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Soft delete pekerjaan",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "400": {"description": "ID tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/pekerjaan/alumni/{alumni_id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Get pekerjaan by Alumni ID",
                "parameters": [
                    {"name": "alumni_id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "pekerjaan list"},
                    "400": {"description": "Alumni ID tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/photo/upload": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Upload photo",
                "consumes": ["multipart/form-data"],
                "parameters": [
                    {"name": "file", "in": "formData", "required": true, "type": "file"},
                    {"name": "alumni_id", "in": "formData", "required": true, "type": "string"}
                ],
                "responses": {
                    "201": {"description": "upload success"},
                    "400": {"description": "File atau alumni_id tidak valid"},
                    "403": {"description": "Permission denied"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/certificate/upload": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Upload certificate",
                "consumes": ["multipart/form-data"],
                "parameters": [
                    {"name": "file", "in": "formData", "required": true, "type": "file"},
                    {"name": "alumni_id", "in": "formData", "required": true, "type": "string"}
                ],
                "responses": {
                    "201": {"description": "upload success"},
                    "400": {"description": "File atau alumni_id tidak valid"},
                    "403": {"description": "Permission denied"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/photo/{alumni_id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Get photo by Alumni ID",
                "parameters": [
                    {"name": "alumni_id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "photo data"},
                    "404": {"description": "Foto tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/certificate/{alumni_id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Get certificate by Alumni ID",
                "parameters": [
                    {"name": "alumni_id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "certificate data"},
                    "404": {"description": "Sertifikat tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/photo/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Delete photo",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "403": {"description": "Permission denied"},
                    "404": {"description": "Foto tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        },
        "/files/certificate/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Files"],
                "summary": "Delete certificate",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "403": {"description": "Permission denied"},
                    "404": {"description": "Sertifikat tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Users"],
                "summary": "Soft delete user",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "400": {"description": "ID tidak valid"},
                    "500": {"description": "error"}
                }
            }
        },
        "/trash/pekerjaan": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Get trashed pekerjaan",
                "responses": {
                    "200": {"description": "trashed data list"},
                    "500": {"description": "error"}
                }
            }
        },
        "/trash/pekerjaan/{id}/restore": {
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Restore pekerjaan dari trash",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "400": {"description": "ID tidak valid"},
                    "404": {"description": "Data tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        },
        "/trash/pekerjaan/{id}/permanent": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Pekerjaan"],
                "summary": "Hard delete pekerjaan secara permanent",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "success response"},
                    "400": {"description": "ID tidak valid"},
                    "404": {"description": "Data tidak ditemukan"},
                    "500": {"description": "error"}
                }
            }
        }
    },
    "schemes": ["http"],
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Type \"Bearer\" followed by a space and JWT token."
        }
    },
    "swagger": "2.0"
}`

// SwaggerInfo holds exported Swagger Definition.
type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds all exported info about this API.
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:3000",
	BasePath:    "/api",
	Schemes:     []string{"http"},
	Title:       "Alumni Management API",
	Description: "API untuk mengelola data alumni dengan MongoDB menggunakan Clean Architecture",
}

func init() {
	swag.Register("swagger", &swag.Spec{
		Version:          SwaggerInfo.Version,
		Host:             SwaggerInfo.Host,
		BasePath:         SwaggerInfo.BasePath,
		Schemes:          SwaggerInfo.Schemes,
		Title:            SwaggerInfo.Title,
		Description:      SwaggerInfo.Description,
		InfoInstanceName: "swagger",
		SwaggerTemplate:  docTemplate,
	})
}
